import streamlit as st
import pandas as pd
from pathlib import Path

# 1. Page Configuration
st.set_page_config(
    page_title="JKK + UR Tracker Dashboard",
    page_icon="🏠",
    layout="wide"
)

# Constants
DATA_DIR = Path("data")
FILE_MAP = {
    "English": DATA_DIR / "listings_english.tsv",
    "Japanese": DATA_DIR / "listings.tsv"
}

# 2. Dataset Toggle (Sidebar)
st.sidebar.title("Configuration")
selected_lang = st.sidebar.radio(
    "Select Dataset Language",
    options=list(FILE_MAP.keys()),
    index=0
)

# 3. Optimized Data Loading
@st.cache_data
def load_data(file_path):
    """Loads a .tsv file and returns a pandas DataFrame."""
    try:
        if not file_path.exists():
            raise FileNotFoundError(f"File not found: {file_path}")
        df = pd.read_csv(file_path, sep='\t')
        return df
    except FileNotFoundError as e:
        st.error(f"Error: {e}")
        return None
    except Exception as e:
        st.error(f"An unexpected error occurred: {e}")
        return None

# Load the selected dataset
df = load_data(FILE_MAP[selected_lang])

if df is not None:
    # 4. Column Filtering (Sidebar)
    st.sidebar.subheader("Display Settings")
    all_columns = df.columns.tolist()
    selected_columns = st.sidebar.multiselect(
        "Select Columns to Display",
        options=all_columns,
        default=all_columns
    )

    # 5. Main Display
    st.title("🏠 JKK + UR Tracker Data Explorer")
    st.subheader(f"Current View: {selected_lang} Dataset")

    # Metrics
    col1, col2 = st.columns(2)
    with col1:
        st.metric("Total Listings", len(df))
    with col2:
        st.metric("Displayed Columns", len(selected_columns))

    # Dataframe rendering
    if selected_columns:
        st.dataframe(
            df[selected_columns],
            use_container_width=True,
            hide_index=True
        )
    else:
        st.warning("Please select at least one column to display.")
else:
    st.info("Please ensure the data files are generated by running the tracker first.")
